create table cliente (
	id_cliente INT PRIMARY KEY,
	nome VARCHAR(50),
	sexo CHAR(1),
	idade INT,
	bairro VARCHAR(50)
);

insert into cliente (id_cliente, nome, sexo, idade, bairro) values (1, 'Giorgio Leggis', 'F', 22, 'Lapa');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (2, 'Gregorio Moysey', 'M', 80, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (3, 'Leontine Pamphilon', 'F', 26, 'Pantanal');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (4, 'Livia Della Scala', 'M', 46, 'Tijuca');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (5, 'Parrnell Hawes', 'M', 55, 'Aterro do Flamengo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (6, 'Yalonda Riddiford', 'M', 64, 'Olavo Bilac');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (7, 'Haslett Blackford', 'F', 54, 'Pilar');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (8, 'Latrina Pentony', 'F', 67, 'Jardim 25 de Agosto');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (9, 'Daffy Killingsworth', 'F', 52, 'Pilar');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (10, 'Sigfrid Ximenez', 'F', 25, 'Aterro do Flamengo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (11, 'Giraldo Guswell', 'M', 33, 'Chacrinha');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (12, 'Tybi Illesley', 'M', 58, 'Lote XV');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (13, 'Uriel Bulteel', 'M', 53, 'São Vicente');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (14, 'Stephen Bulfit', 'M', 66, 'Gramacho');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (15, 'Kala Raoul', 'M', 33, 'Jardim 25 de Agosto');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (16, 'Willie Beet', 'F', 64, 'Botafogo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (17, 'Jake Dalgliesh', 'M', 33, 'Lote XV');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (18, 'Langsdon Kinnear', 'M', 49, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (19, 'Aloisia Hansod', 'M', 68, 'Lote XV');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (20, 'Winnifred Maven', 'M', 30, 'Pantanal');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (21, 'Sherman Withers', 'M', 62, 'Aterro do Flamengo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (22, 'Kane Copcott', 'F', 49, 'Olavo Bilac');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (23, 'Felic Schankelborg', 'M', 68, 'Lapa');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (24, 'Gerti Ewdale', 'F', 56, 'São Vicente');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (25, 'Caresa Arntzen', 'F', 58, 'Pantanal');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (26, 'Sherry Cogman', 'M', 71, 'Jardim 25 de Agosto');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (27, 'Ortensia Lorne', 'M', 61, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (28, 'Denny Lambarton', 'F', 38, 'Leblon');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (29, 'Darci Pottes', 'M', 51, 'Leblon');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (30, 'Willa Coghlan', 'F', 29, 'Chacrinha');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (31, 'Mandy Tree', 'M', 81, 'Tijuca');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (32, 'Catlee Berzon', 'F', 61, 'Jardim 25 de Agosto');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (33, 'Aeriela Meadows', 'F', 35, 'Lapa');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (34, 'Elliot Harper', 'M', 57, 'Leme');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (35, 'Mandi Cogman', 'F', 80, 'Tijuca');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (36, 'Kimberley Schooling', 'M', 48, 'Botafogo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (37, 'Stormy Norgate', 'M', 55, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (38, 'Matti Olivetti', 'F', 31, 'Olavo Bilac');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (39, 'Justin Rudwell', 'F', 41, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (40, 'Gabriel Speeks', 'F', 66, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (41, 'Ulrica Kibel', 'F', 67, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (42, 'Farrand Kennerknecht', 'M', 31, 'Pantanal');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (43, 'Annecorinne O''Hern', 'M', 30, 'Gramacho');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (44, 'Eden Bielfelt', 'F', 81, 'Vila São Luís');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (45, 'Ninetta Duckit', 'M', 79, 'Vila São Luís');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (46, 'Erhard Bennit', 'M', 46, 'São Conrado');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (47, 'Noel Batchelar', 'F', 25, 'Lote XV');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (48, 'Staford Whistan', 'F', 39, 'Pantanal');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (49, 'Louella Fouch', 'F', 62, 'Leblon');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (50, 'Orin Wilding', 'F', 21, 'Pantanal');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (51, 'Mavra Bowick', 'F', 68, 'São Vicente');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (52, 'Johny Deacon', 'M', 43, 'Jardim 25 de Agosto');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (53, 'Zacharie Bulluck', 'F', 65, 'Botafogo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (54, 'Chucho Freed', 'F', 85, 'Jardim 25 de Agosto');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (55, 'Jodie Leadstone', 'M', 49, 'São Vicente');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (56, 'Charmane Bisatt', 'F', 56, 'Pilar');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (57, 'Augusto Kleeborn', 'F', 55, 'Lote XV');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (58, 'Sybil Biggin', 'F', 60, 'Xerem');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (59, 'Rochester Bastin', 'F', 20, 'Jardim 25 de Agosto');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (60, 'Denise Bushaway', 'F', 52, 'Botafogo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (61, 'Sonni Morgan', 'M', 28, 'Lapa');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (62, 'Audre Batte', 'F', 84, 'Chacrinha');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (63, 'Julianne Borthe', 'M', 25, 'Aterro do Flamengo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (64, 'Jillana Doogan', 'F', 38, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (65, 'Thorsten Waylen', 'F', 39, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (66, 'Hansiain Armytage', 'F', 36, 'Vila São Luís');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (67, 'Mindy Pestridge', 'F', 24, 'São Conrado');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (68, 'Emmett Hartus', 'M', 55, 'Pantanal');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (69, 'Bettina Tulley', 'F', 63, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (70, 'Dorothea Abelwhite', 'M', 51, 'São Conrado');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (71, 'Giusto Perchard', 'M', 85, 'Jardim 25 de Agosto');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (72, 'Kamillah Yakovich', 'F', 37, 'Pilar');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (73, 'Jorry Geydon', 'M', 21, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (74, 'Padriac Lidden', 'F', 64, 'Pantanal');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (75, 'Rowena Powney', 'F', 85, 'Jardim 25 de Agosto');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (76, 'Lefty Wanne', 'F', 55, 'Olavo Bilac');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (77, 'Lindi Gammill', 'F', 25, 'Chacrinha');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (78, 'Jerrilyn Irce', 'M', 77, 'Xerem');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (79, 'Jim Airy', 'M', 20, 'Pantanal');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (80, 'Jim Beggs', 'M', 46, 'Aterro do Flamengo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (81, 'Nicko Seaborne', 'F', 58, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (82, 'Liana Southgate', 'F', 25, 'Pilar');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (83, 'Emelia Popov', 'F', 74, 'São Vicente');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (84, 'Dean Bankhurst', 'F', 39, 'Gramacho');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (85, 'Russell Georg', 'F', 45, 'Xerem');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (86, 'Cthrine Dring', 'F', 27, 'Jardim 25 de Agosto');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (87, 'Baldwin Tuite', 'M', 30, 'São Conrado');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (88, 'Arabelle Joselevitch', 'F', 83, 'Aterro do Flamengo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (89, 'Ava Golland', 'M', 18, 'São Conrado');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (90, 'Dion Noell', 'F', 84, 'Xerem');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (91, 'Lizabeth Deners', 'F', 39, 'Lapa');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (92, 'Meggi Casperri', 'F', 69, 'Botafogo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (93, 'Glori Frowen', 'F', 19, 'Lapa');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (94, 'Catherin Fieller', 'F', 84, 'São Vicente');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (95, 'Clayborn Cornau', 'F', 61, 'Pilar');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (96, 'Anthe Curton', 'F', 29, 'Leme');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (97, 'Martica McClymond', 'F', 56, 'Chacrinha');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (98, 'Lucinda Selland', 'M', 17, 'Leme');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (99, 'Michelle Barniss', 'M', 68, 'Olavo Bilac');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (100, 'Salaidh Juschke', 'F', 29, 'Olavo Bilac');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (101, 'Harland Durant', 'F', 81, 'Leme');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (102, 'Gayelord Kilby', 'M', 47, 'Leblon');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (103, 'Emmie Bensley', 'M', 33, 'Lote XV');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (104, 'Beilul Reolfo', 'M', 81, 'Gramacho');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (105, 'Ashlin Erskin', 'F', 40, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (106, 'Beryl Glencrosche', 'F', 76, 'Lapa');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (107, 'Ferdinande McDuall', 'M', 58, 'Botafogo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (108, 'Rosabel Blasio', 'F', 29, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (109, 'Mattie Levett', 'F', 75, 'Botafogo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (110, 'Dianna Godehard.sf', 'F', 42, 'Chacrinha');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (111, 'Coralie Merill', 'M', 51, 'Pantanal');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (112, 'Ivan Dumbar', 'M', 49, 'Ipanema');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (113, 'Nerissa Capey', 'F', 41, 'Chacrinha');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (114, 'Melissa Dunkerk', 'F', 65, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (115, 'Desirae Brevetor', 'F', 18, 'Pilar');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (116, 'Pearl O''Corrigane', 'M', 59, 'Gramacho');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (117, 'Kassey Cruden', 'M', 20, 'Aterro do Flamengo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (118, 'Isobel Da Costa', 'F', 75, 'Jardim 25 de Agosto');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (119, 'Sarina Dyer', 'F', 82, 'Leme');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (120, 'Aldous Camier', 'F', 70, 'Olavo Bilac');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (121, 'Curtis Asple', 'F', 29, 'Tijuca');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (122, 'Ezra McCrum', 'M', 51, 'São Conrado');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (123, 'Thorvald L''Episcopi', 'M', 51, 'Tijuca');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (124, 'Pancho Sneller', 'F', 33, 'Ipanema');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (125, 'Stirling McWhan', 'M', 71, 'Leme');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (126, 'Adan Hooke', 'M', 16, 'Aterro do Flamengo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (127, 'Kayla Aingel', 'M', 72, 'Xerem');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (128, 'Laughton Geffcock', 'M', 19, 'Olavo Bilac');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (129, 'Bartram Scalia', 'F', 44, 'Pantanal');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (130, 'Hilarius Mintoff', 'F', 50, 'Lote XV');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (131, 'Karlene Weddeburn', 'F', 75, 'Pilar');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (132, 'Gretal Monro', 'F', 34, 'Pilar');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (133, 'Myrvyn Linge', 'M', 78, 'Pilar');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (134, 'Roseann Liddall', 'M', 82, 'Tijuca');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (135, 'Ingamar Showell', 'F', 73, 'Pantanal');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (136, 'Davin Imason', 'F', 39, 'Vila São Luís');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (137, 'Magdaia Hince', 'M', 76, 'Vila São Luís');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (138, 'Willey Frye', 'M', 68, 'Pantanal');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (139, 'Wolfgang Degue', 'F', 72, 'Botafogo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (140, 'Colene Guille', 'M', 84, 'Pilar');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (141, 'Dianna Kuhwald', 'M', 65, 'Pantanal');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (142, 'Gabrila Ranscome', 'M', 27, 'Olavo Bilac');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (143, 'Clevie Ludwig', 'M', 84, 'Aterro do Flamengo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (144, 'Bryana Gittings', 'F', 80, 'Pantanal');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (145, 'Anneliese Antognelli', 'M', 46, 'Pantanal');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (146, 'Isadora Stefanovic', 'M', 26, 'Xerem');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (147, 'Lorianna Russe', 'F', 73, 'Botafogo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (148, 'Granny Batteson', 'M', 24, 'São Vicente');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (149, 'Jocelyne Bonallick', 'M', 23, 'Lote XV');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (150, 'Rosetta Scawen', 'F', 25, 'Aterro do Flamengo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (151, 'Benoit Melan', 'M', 25, 'Jardim 25 de Agosto');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (152, 'Yuma Tompkiss', 'F', 47, 'Botafogo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (153, 'Enrika Yeo', 'M', 69, 'Xerem');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (154, 'Petronilla Lazonby', 'M', 34, 'Gramacho');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (155, 'Gardner Brozek', 'F', 65, 'Olavo Bilac');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (156, 'Mart Mattke', 'M', 29, 'Pilar');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (157, 'Ellynn Dearl', 'F', 46, 'Chacrinha');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (158, 'Morgun Shower', 'M', 76, 'Olavo Bilac');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (159, 'Kassi McVicar', 'F', 61, 'São Vicente');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (160, 'Phedra Volonte', 'F', 52, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (161, 'Herschel Kaasman', 'M', 59, 'Leme');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (162, 'Vicky Giggie', 'F', 27, 'Botafogo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (163, 'Steffen Boutell', 'F', 64, 'Chacrinha');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (164, 'Rania Duffan', 'M', 32, 'Pantanal');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (165, 'Dianemarie Cowell', 'F', 46, 'Xerem');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (166, 'Dane Wilson', 'F', 49, 'Lote XV');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (167, 'Zechariah Jacquemy', 'F', 31, 'Gramacho');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (168, 'Bari Baton', 'F', 47, 'Tijuca');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (169, 'Pepita Emmatt', 'M', 16, 'Vila São Luís');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (170, 'Bo Cardenoso', 'M', 73, 'Jardim 25 de Agosto');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (171, 'Arlena Hargraves', 'F', 32, 'Pilar');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (172, 'Sephira Marven', 'M', 62, 'Vila São Luís');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (173, 'Desiri Frammingham', 'M', 78, 'Jardim 25 de Agosto');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (174, 'Tori Egdal', 'M', 77, 'São Vicente');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (175, 'Josh Morfell', 'F', 40, 'Leme');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (176, 'Veda Leon', 'M', 21, 'São Conrado');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (177, 'Anet Simenot', 'F', 17, 'Chacrinha');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (178, 'Jeniffer Hansed', 'F', 35, 'Xerem');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (179, 'Nonah Yearn', 'F', 18, 'Gramacho');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (180, 'Gannon Cadogan', 'F', 68, 'Botafogo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (181, 'Constantina Izakof', 'F', 68, 'Tijuca');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (182, 'Claudio Karlicek', 'M', 83, 'Gramacho');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (183, 'Yehudit O''Cannon', 'F', 21, 'Botafogo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (184, 'Rori Monkton', 'M', 31, 'São Conrado');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (185, 'Cathryn Carvell', 'F', 82, 'São Vicente');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (186, 'Elle Bredgeland', 'F', 38, 'Gramacho');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (187, 'Gard Meynell', 'F', 18, 'Jardim 25 de Agosto');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (188, 'Witty Kayley', 'F', 53, 'Pantanal');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (189, 'Ferdinande Salvati', 'F', 61, 'Xerem');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (190, 'Marisa MacCumeskey', 'M', 41, 'Olavo Bilac');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (191, 'Tuck Blackledge', 'M', 59, 'Xerem');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (192, 'Sandy Fitzpatrick', 'M', 28, 'Vila São Luís');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (193, 'Angelique Finlay', 'M', 21, 'Ipanema');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (194, 'Danica Eddy', 'M', 61, 'Ipanema');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (195, 'Sondra Millichap', 'F', 23, 'Leme');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (196, 'Peta Lathom', 'M', 52, 'Olavo Bilac');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (197, 'Dodi Simoncelli', 'F', 64, 'Lapa');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (198, 'Cordelie Braunroth', 'M', 62, 'Tijuca');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (199, 'Rafe Wones', 'F', 59, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (200, 'Fina Maas', 'M', 61, 'Lapa');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (201, 'Inez Shillingford', 'F', 34, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (202, 'Belle Branni', 'F', 61, 'Tijuca');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (203, 'Morissa Norker', 'M', 54, 'Lapa');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (204, 'Garvin Nuton', 'M', 53, 'Olavo Bilac');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (205, 'Terry Reily', 'F', 41, 'Tijuca');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (206, 'Wilmette Hemeret', 'F', 63, 'Xerem');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (207, 'Paulina Kinsey', 'F', 18, 'Lapa');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (208, 'Broddy Trimming', 'M', 47, 'Gramacho');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (209, 'Ammamaria Eadmead', 'M', 33, 'Gramacho');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (210, 'Kendricks Pero', 'F', 82, 'Tijuca');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (211, 'Jarad Minger', 'F', 85, 'Pantanal');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (212, 'Brina Heald', 'M', 70, 'Gramacho');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (213, 'Daisie Tunnacliffe', 'M', 54, 'Chacrinha');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (214, 'Brooke Pedroni', 'F', 16, 'Gramacho');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (215, 'Lalo Riping', 'F', 60, 'Vila São Luís');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (216, 'Druci Frossell', 'F', 29, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (217, 'Reynolds Cashman', 'M', 85, 'São Vicente');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (218, 'Trescha Tantrum', 'F', 84, 'Xerem');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (219, 'Marika Hewkin', 'M', 49, 'Jardim 25 de Agosto');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (220, 'Fancie Winson', 'F', 59, 'Leme');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (221, 'Dana Matveichev', 'M', 60, 'Tijuca');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (222, 'Winnie Scud', 'M', 85, 'Xerem');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (223, 'Sianna Frankes', 'F', 18, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (224, 'Udale Rodders', 'F', 30, 'Vila São Luís');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (225, 'Buffy Rodolphe', 'F', 26, 'Chacrinha');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (226, 'Terence Mapother', 'F', 63, 'Pantanal');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (227, 'Dode Veschambes', 'M', 73, 'Jardim 25 de Agosto');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (228, 'Arturo Escritt', 'F', 47, 'Leme');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (229, 'Julia Bate', 'M', 58, 'Tijuca');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (230, 'Mae Baddam', 'F', 49, 'Pantanal');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (231, 'Crin Philipsen', 'M', 41, 'Pilar');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (232, 'Claiborne Sworne', 'M', 33, 'Vila São Luís');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (233, 'Jedd Wildsmith', 'M', 71, 'Leblon');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (234, 'Jerad Hebditch', 'M', 61, 'Gramacho');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (235, 'Jo-anne Blasl', 'F', 31, 'Pantanal');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (236, 'Sephira Kirman', 'M', 24, 'Chacrinha');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (237, 'Cherye Scrase', 'F', 55, 'Vila São Luís');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (238, 'Amalee Seary', 'M', 62, 'Chacrinha');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (239, 'Arnold Dummigan', 'F', 63, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (240, 'Deonne Trayford', 'F', 22, 'São Vicente');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (241, 'Codie Elleray', 'F', 29, 'Gramacho');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (242, 'Kiri Juara', 'F', 53, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (243, 'Gerri Emilien', 'M', 61, 'Tijuca');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (244, 'Lovell Causley', 'M', 68, 'Leme');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (245, 'Cammie Beernt', 'F', 65, 'Tijuca');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (246, 'Nanni Quinn', 'F', 54, 'São Vicente');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (247, 'Emmalynn Oloshin', 'M', 50, 'Botafogo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (248, 'Nevins Quade', 'F', 19, 'Leme');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (249, 'Myca Orniz', 'F', 39, 'São Conrado');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (250, 'Verene Sextie', 'M', 33, 'São Conrado');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (251, 'Farlee Mitham', 'F', 44, 'São Conrado');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (252, 'Dian Atte-Stone', 'F', 59, 'Lapa');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (253, 'Allin Gresley', 'F', 20, 'Leblon');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (254, 'Marys Rulten', 'M', 84, 'São Vicente');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (255, 'Jamima Normansell', 'M', 49, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (256, 'Axel Twallin', 'M', 69, 'Ipanema');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (257, 'Glynnis Sygrove', 'F', 36, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (258, 'Kalina Affron', 'F', 44, 'Lapa');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (259, 'Dominique Balnave', 'M', 58, 'Botafogo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (260, 'Ansley Streeten', 'F', 20, 'Pilar');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (261, 'Justina Commusso', 'F', 34, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (262, 'Riobard Awty', 'M', 43, 'Chacrinha');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (263, 'Veronica Grut', 'F', 26, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (264, 'Doug Cobbe', 'M', 24, 'Pilar');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (265, 'Oren Howat', 'F', 81, 'Gramacho');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (266, 'Paulie Dobrowski', 'F', 78, 'Gramacho');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (267, 'Jacobo Kingston', 'M', 31, 'Botafogo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (268, 'Hattie Gosnall', 'F', 45, 'Lote XV');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (269, 'Tate Duferie', 'F', 46, 'Chacrinha');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (270, 'Luther Elford', 'M', 54, 'São Conrado');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (271, 'Christine De Roeck', 'M', 17, 'Aterro do Flamengo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (272, 'Frannie Bitcheno', 'F', 53, 'São Conrado');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (273, 'Silvano Gudge', 'M', 28, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (274, 'Kamillah Seifert', 'F', 18, 'Pilar');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (275, 'Zilvia Beacom', 'M', 77, 'Leblon');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (276, 'Marie-ann McCraw', 'F', 68, 'Gramacho');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (277, 'Ernestine Fain', 'M', 51, 'Botafogo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (278, 'Carson Pontefract', 'M', 37, 'Pilar');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (279, 'Keefer Culter', 'M', 25, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (280, 'Fransisco Di Ruggero', 'M', 34, 'Lapa');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (281, 'Aprilette Conerding', 'M', 69, 'Pilar');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (282, 'Anny Haxbie', 'F', 40, 'Aterro do Flamengo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (283, 'Elsbeth Meriot', 'F', 82, 'Pilar');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (284, 'Jolie Huyche', 'F', 28, 'Pilar');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (285, 'Val Crux', 'M', 39, 'Olavo Bilac');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (286, 'Anthea Bailes', 'F', 19, 'Ipanema');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (287, 'Agathe Mauchline', 'M', 80, 'Ipanema');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (288, 'Roldan Ellicock', 'M', 60, 'Pilar');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (289, 'My Rothschild', 'M', 65, 'Santa Cruz da Serra');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (290, 'Quinton Shorey', 'M', 61, 'Olavo Bilac');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (291, 'Bailie Newcom', 'M', 39, 'Pantanal');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (292, 'Shelba Alejandro', 'M', 34, 'Lapa');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (293, 'Romain Tyer', 'F', 70, 'Aterro do Flamengo');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (294, 'Cash Cullagh', 'M', 37, 'Lapa');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (295, 'Yule Alennikov', 'F', 30, 'Lote XV');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (296, 'Phebe Cornall', 'F', 63, 'Chacrinha');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (297, 'Durward Kerss', 'M', 58, 'Tijuca');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (298, 'Jackson D''Aeth', 'F', 60, 'Gramacho');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (299, 'Olivia Iston', 'F', 84, 'Gramacho');
insert into cliente (id_cliente, nome, sexo, idade, bairro) values (300, 'Kerwinn Rowlett', 'F', 23, 'Leme');
